import {
  BarChart3,
  Bug,
  BookOpen,
  Brain,
  Briefcase,
  Calendar,
  ClipboardList,
  Code2,
  Compass,
  Cpu,
  Database,
  DollarSign,
  FileText,
  FlaskConical,
  GitBranch,
  Globe,
  Heart,
  Image,
  Languages,
  Layers,
  Lightbulb,
  Lock,
  Mail,
  Megaphone,
  MessageSquare,
  Music,
  Palette,
  PenTool,
  Rocket,
  Scale,
  Search,
  Shield,
  Sparkles,
  Target,
  Terminal,
  Users,
  Video,
  Wand2,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'
import type { SymbolName } from './symbolNames.ts'

export const symbolIcons: Record<SymbolName, LucideIcon> = {
  sparkles: Sparkles,
  search: Search,
  code: Code2,
  terminal: Terminal,
  bug: Bug,
  'git-branch': GitBranch,
  database: Database,
  cpu: Cpu,
  rocket: Rocket,
  zap: Zap,
  wand: Wand2,
  brain: Brain,
  lightbulb: Lightbulb,
  target: Target,
  compass: Compass,
  palette: Palette,
  'pen-tool': PenTool,
  image: Image,
  video: Video,
  music: Music,
  'file-text': FileText,
  book: BookOpen,
  clipboard: ClipboardList,
  languages: Languages,
  message: MessageSquare,
  mail: Mail,
  megaphone: Megaphone,
  chart: BarChart3,
  dollar: DollarSign,
  briefcase: Briefcase,
  scale: Scale,
  shield: Shield,
  lock: Lock,
  users: Users,
  calendar: Calendar,
  globe: Globe,
  layers: Layers,
  flask: FlaskConical,
  wrench: Wrench,
  heart: Heart,
}
